#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-fastjsonschema
Version  : 2.15.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/c6/b1/01e6c2fee5a423e7ae8ce3cb66a119e1ec987add3a21b5c3ca25628f025c/fastjsonschema-2.15.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c6/b1/01e6c2fee5a423e7ae8ce3cb66a119e1ec987add3a21b5c3ca25628f025c/fastjsonschema-2.15.1.tar.gz
Summary  : Fastest Python implementation of JSON schema
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-fastjsonschema-license = %{version}-%{release}
Requires: pypi-fastjsonschema-python = %{version}-%{release}
Requires: pypi-fastjsonschema-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Fast JSON schema for Python
        ===========================
        
        |PyPI| |Pythons|

%package license
Summary: license components for the pypi-fastjsonschema package.
Group: Default

%description license
license components for the pypi-fastjsonschema package.


%package python
Summary: python components for the pypi-fastjsonschema package.
Group: Default
Requires: pypi-fastjsonschema-python3 = %{version}-%{release}

%description python
python components for the pypi-fastjsonschema package.


%package python3
Summary: python3 components for the pypi-fastjsonschema package.
Group: Default
Requires: python3-core
Provides: pypi(fastjsonschema)

%description python3
python3 components for the pypi-fastjsonschema package.


%prep
%setup -q -n fastjsonschema-2.15.1
cd %{_builddir}/fastjsonschema-2.15.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639057693
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-fastjsonschema
cp %{_builddir}/fastjsonschema-2.15.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-fastjsonschema/b15833fac355dbd5f534e0cbc928a2ca38f7d551
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-fastjsonschema/b15833fac355dbd5f534e0cbc928a2ca38f7d551

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
